---
title: "Best wine searcher"
---



```{r}
library(tidyverse)
library(highcharter)
library(DT)

wine <- read_csv("winemag-data-130k-v2.csv")
varwine <- wine %>% 
  select(country, points, variety) %>% 
  group_by(country, variety) %>% 
  summarise(var_mean_points = mean(points)) %>% 
  ungroup() 
```
```{r}
data(GNI2014, package = "treemap")

wine_points <- wine |>
    filter(!is.na(province), !is.na(price)) |>
    mutate(country = ifelse(country=="US", "United States", country)) |>
    mutate(country = ifelse(country=="Macedonia", "Macedonia, FYR", country)) |>
    mutate(country = ifelse(country=="Slovakia", "Slovak Republic", country)) |>
    mutate(country = ifelse(country=="England", "United Kingdom", country)) |>
    group_by(country) |>
    summarise(avg_points = mean(points), .groups = "drop") |>
    left_join(GNI2014 |> dplyr::select(iso3, country) |> distinct(), by = "country")

```
```{r}
# best wine in each country
best_wine_by_country <- wine |>
  filter(!is.na(province), !is.na(price)) |>
  mutate(country = ifelse(country=="US", "United States", country)) |>
  mutate(country = ifelse(country=="Macedonia", "Macedonia, FYR", country)) |>
  mutate(country = ifelse(country=="Slovakia", "Slovak Republic", country)) |>
  mutate(country = ifelse(country=="England", "United Kingdom", country)) |>
  group_by(country) |>
  slice_max(points, n = 1, with_ties = FALSE) |>
  ungroup() |>
  select(country, best_wine = title, best_points = points)

wine_points <- wine_points |>
  left_join(best_wine_by_country, by = "country")
```
```{r}
#| column: margin
#| fig-height: 2.5
wine_points %>% arrange(desc(avg_points)) %>% head(5) %>% 
  hchart(type="column", hcaes(x=country, y= avg_points))

```
```{r}
#| label: fig-province-points
#| fig-height: 5
hcmap(map = "custom/world-robinson-lowres",
  download_map_data = getOption("highcharter.download_map_data"),
  data = wine_points,
  value = "avg_points",
  joinBy = c("iso-a3", "iso3")) |>
    hc_colorAxis(stops = color_stops(colors = viridisLite::inferno(10, begin = 0.1))) |>
    hc_tooltip(pointFormat = "<b>{point.name}</b><br>Avg points: {point.value:.1f}<br>Top wine: {point.best_wine} ({point.best_points} pts)")
```
@fig-province-points shows the average points by country.



```{r}
#| label: tbl-cap

wine %>% select(country, points, price, province, variety, title) %>%
  mutate(year = as.numeric(str_extract(title, "\\d{4}"))) %>%
  select(-title) %>%
  datatable()
```
@tbl-cap Shows the overall wine quality in the world











```{r}
#| label: fig-avrpoints
varwine %>% 
  mutate(countryvariety = paste(country, variety, sep = "_")) %>% 
  arrange(desc(var_mean_points)) %>% 
  head(100) %>% 
  ungroup() %>% 
  hchart("column", hcaes(x= countryvariety, y = var_mean_points))|>
  hc_xAxis(title = list(text = "Country / Variety")) |>
  hc_yAxis(title = list(text = "Mean Score (pts)"))
```
@fig-avrpoints shows the sorted average quality by wine type and country.